base_url = 'https://petstore.swagger.io/v2'
add_pet_store_url = f"{base_url}/pet"
image_path = r"C:\Users\arunroshan.r\Pictures\Screenshots\data not visable.png"
status_values = ["sold", "available", "pending"]
pet_order_url = f"{base_url}/store/order"
user_url = f"{base_url}/user"
login_user_url = f"{base_url}/user/login"
logout_user_url = f"{base_url}/user/logout"
pet_url = f"{base_url}/pet"
pet_status_url = f"{base_url}/pet/findByStatus"
inventory_url = f"{base_url}/store/inventory"
pet_id = 2048
new_animal_name = 'lion'
animal_name = "Buddy"
pet_status = "available"
api_key = "Atmecs#1234"
update_username = "ArunRoshan"
